export { default as Body } from './Body'
export { default as Data } from './Data'
export { default as Head } from './Head'
export { default as Header } from './Header'
export { default as Row } from './Row'
export { default as Main } from './Table'
